version: '3.8'

services:
  sensor-api:
    build:
      context: ../../
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - sensor-data:/app/data
    environment:
      - DATABASE_PATH=/app/data/sensor_data.db
      - RUST_LOG=sensor_monitoring_api=info,tower_http=info
      - PORT=3000
    networks:
      - sensor-network

  client-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - API_BASE_URL=http://sensor-api:3000/api
      - RUST_LOG=sensor_client_app=info,tower_http=info
      - PORT=8080
      - HOST=0.0.0.0
    depends_on:
      - sensor-api
    networks:
      - sensor-network

networks:
  sensor-network:
    driver: bridge

volumes:
  sensor-data: